### ISSUE TITLE
E2e Test is not running it fails with a message saying "Angular Couldn't be found on the page..., if this is not an angular application, you may need to turn of waiting for angular. 

### ISSUE THREAD

**Issue by PrajwalRavichandra** [mattwilson1024/angular-hybrid#1]

**Comment by mattwilson1024** [comment]
Hi @PrajwalAr. I'm not planning on maintaining or updating this repo any more - having completed my Angular migration some time ago, I'm only really keeping this repo here as a historical reference. I do recall have issues with Protractor during the Angular migration on our app, but I can't remember the details and we switched to Cypress so it's not something I am able to help with I'm afraid.

**Comment by PrajwalRavichandra** [comment]
Thanks @mattwilson1024 , that was helpful. 👍
